"""
This type stub file was generated by pyright.
"""

"""
Models that behave the same as Anki's built-in models ("Basic", "Basic (and reversed card)", "Cloze", etc.).

Note: Anki does not assign consistent IDs to its built-in models (see
    https://github.com/kerrickstaley/genanki/issues/55#issuecomment-717687667 and
    https://forums.ankiweb.net/t/exported-basic-cards-create-duplicate-card-types-when-imported-by-other-users/959 ).
    Because of this, we cannot simply call these models "Basic" etc. If we did, then when importing a genanki-generated
    deck, Anki would see a model called "Basic" which has a different model ID than its internal "Basic" model, and it
    would rename the imported model to something like "Basic-123abc". Instead, we name the models "Basic (genanki)"
    etc., which is less confusing.
"""
from genanki.model import Model

BASIC_MODEL: Model = ...
BASIC_AND_REVERSED_CARD_MODEL: Model = ...
BASIC_OPTIONAL_REVERSED_CARD_MODEL: Model = ...
BASIC_TYPE_IN_THE_ANSWER_MODEL: Model = ...
CLOZE_MODEL: Model = ...
