"""
This type stub file was generated by pyright.
"""

from sqlite3 import Cursor

class Card:
    def __init__(self, ord, suspend=...) -> None: ...
    def write_to_db(
        self, cursor: Cursor, timestamp: float, deck_id, note_id, id_gen, due=...
    ) -> None: ...
