"""
This type stub file was generated by pyright.
"""

class Card:
    def __init__(self, ord, suspend=...) -> None: ...
    def write_to_db(
        self, cursor, timestamp: float, deck_id, note_id, id_gen, due=...
    ):  # -> None:
        ...
