"""
This type stub file was generated by pyright.
"""

class Model:
    FRONT_BACK = ...
    CLOZE = ...
    DEFAULT_LATEX_PRE = ...
    DEFAULT_LATEX_POST = ...
    def __init__(
        self,
        model_id=...,
        name=...,
        fields=...,
        templates=...,
        css=...,
        model_type=...,
        latex_pre=...,
        latex_post=...,
        sort_field_index=...,
    ) -> None: ...
    def set_fields(self, fields):  # -> None:
        ...

    def set_templates(self, templates):  # -> None:
        ...

    def to_json(self, timestamp: float, deck_id):  # -> dict[str, Any]:
        ...

    def __repr__(self):  # -> str:
        ...
