"""
This type stub file was generated by pyright.
"""

from typing import Any, Literal

from typing_extensions import override

class Model:
    FRONT_BACK: Literal[0] = ...
    CLOZE: Literal[1] = ...
    DEFAULT_LATEX_PRE: str = ...
    DEFAULT_LATEX_POST: str = ...
    def __init__(
        self,
        model_id: int,
        name: str,
        fields: list[dict[str, str]] | str,
        templates: list[dict[str, str]] | str,
        css: str = ...,
        model_type: Literal[0, 1] = ...,
        latex_pre: str = ...,
        latex_post: str = ...,
        sort_field_index: int = ...,
    ) -> None: ...
    def set_fields(self, fields: list[dict[str, str]] | str) -> None: ...
    def set_templates(self, templates: list[dict[str, str]] | str) -> None: ...
    def to_json(self, timestamp: float, deck_id: int) -> dict[str, Any]: ...
    @override
    def __repr__(self) -> str: ...
