"""
This type stub file was generated by pyright.
"""

from typing import Any

from typing_extensions import LiteralString

BASE91_TABLE: list[str] = ...

def guid_for(*values: object) -> LiteralString: ...
